const ARCONNECT_REDIRECT = 'https://www.arconnect.io/';
const ARWEAVE_APP_REDIRECT = 'https://arweave.app/welcome';

export const language = {
	about: `About`,
	aboutView: {
		header1: `Preserving`,
		header2: `Human History`,
		steps: {
			list: [
				{
					header: `Creating Pools`,
					description: `An operator creates a pool. A pool operator can be a historical institution, or anyone that is interested in preserving a topic.`,
					action: {
						label: `Learn About Creating`,
						href: `/create/`,
					},
				},
				{
					header: `Contributing to Pools`,
					description: `Users contribute Arweave tokens ($AR) to pools that they find valuable. These contributions pay for the storage space on Arweave.`,
					action: {
						label: `Learn About Contributing`,
						href: `/contribute/`,
					},
				},
				{
					header: `Preserve Artifacts`,
					description: `Pool operators can now collect artifacts. Documents, books, images, audio clips, videos, etc. within the pool are uploaded to Arweave. Since the artifacts are stored on Arweave, they cannot be changed or removed by anyone.`,
				},
				{
					header: `Collect Artifacts`,
					description: `Contributors will be made the sponsor of an amount of digital artifacts equal to the percentage of their $AR contribution (relative to the total $AR contributed).`,
				},
			],
		},
		subHeader1: `<p>Inspired by the Great Library of Alexandria, the mission of Alex. is to <span>preserve important historical artifacts</span> for the enrichment of all people.</p>`,
		subHeader2: `In order for humanity to move forward, we need to clearly see our past.`,
		detail: {
			artifactTypes: `Artifacts are currently being preserved from:`,
			action: `Learn How to Create`,
			section1: {
				header: 'Alex.',
				description: 'A decentralized archival platform that preserves human history and culture digitally. ',
				footer:
					'Alex. leverages the immutable and permanent data storage of Arweave. Institutions and creators are incentivized to publicly archive digital content by allowing anyone to become sponsors of their digital <b>artifacts</b>. Artifacts are grouped together into <b>pools</b>.',
			},
			section2: {
				header: 'What is a Pool?',
				description: 'A pool is a topic, event, or idea that can be digitally and publicly archived.',
				footer: 'Anyone can create a pool and earn rewards.',
			},
			section3: {
				header: 'What is an Artifact?',
				description:
					'An aritfact is a permanently preserved piece of digital content, including <b>documents</b>, <b>books</b>, <b>images</b>, <b>audio</b>, or <b>videos</b>.',
				footer: 'Artifacts are deployed as assets to Arweave and distributed to the contributors who support the pool.',
			},
		},
		infoDescription1: `<b>Archiving is important.</b> Archives allow people to look back at history to ensure better decisions are made for the future of society. Unfortunately, the current model for archiving is insufficiently incentivized. The person that stores the data, which others can later access without charge, is the person that has to pay. Alex. changes this by allowing the public to sponsor the archiving of digital content.`,
		infoDescription2: `Currently, historical archives are often controlled by a single centralized entity. This means that data can be manipulated or censored to benefit special interests. Therefore <b>Alex. uses Arweave to preserve important historical and cultural information</b> that may otherwise be lost, tampered with, or held hostage in a centralized server.`,
		infoHeader1: `Decentralized Archiving`,
		stepsHeader1: `How it works`,
		subnav: {
			decentralization: 'Decentralization',
			header: 'Alex. Ecosystem',
			howItWorks: 'How it works',
		},
	},
	address: `Address`,
	appName: `Alex.`,
	artifactDetails: `Artifact Details`,
	artifactTypesDisplay: {
		files: `Personal Archives`,
		historical: `Historical Organizations`,
		nostr: `Nostr`,
		messaging: `Twitter`,
		reddit: `Reddit`,
		universities: `Universities`,
		webpage: `Wikipedia`,
	},
	artifactsCreated: `of Artifacts Created`,
	arweaveAppConnectionError: `Connection error with Arweave.app. The connector window must remain open after the initial connection.`,
	accept: `Accept`,
	account: {
		header1: `Account`,
		all: { title: `Artifacts` },
		bookmarks: { title: `Bookmarks` },
		collections: { title: `Collections` },
		contributions: { title: `Contributions` },
		pools: { title: `Pools` },
	},
	actions: `Actions`,
	activePools: `Active Pools`,
	addField: `Add Field`,
	addtoBookmarks: `Add to Bookmarks`,
	amountExceedsBalance: `Amount exceeds Balance`,
	amountExceedsMaxTransferAmount: `Amount exceeds Maximum Transfer Amount`,
	artifact: `Artifact`,
	artifactCount: `Artifact Count`,
	artifactGroup: `Artifact Group`,
	artifactListedForSale: `This artifact has been listed for sale!`,
	artifactPreview: `Artifact Preview`,
	artifactStamped: `Artifact Stamped`,
	artifacts: `Artifacts`,
	artifactDetail: {
		fileInformation: `File Information`,
		viewRaw: `View Raw`,
		tags: `Tags`,
		title: `Title`,
	},
	artifactListingPrice: `Artifact Listing Price`,
	artifactListingPriceInfo: `This value represents the price for each artifact that will be listed in the UCM`,
	arTokens: `$AR`,
	availableBalance: `Available Balance`,
	banner: {
		header1: `A decentralized archival platform that preserves human history and culture digitally.`,
		subheader1: `Archives are permanently stored on`,
		subheader2: `Pools are created with the`,
	},
	basicInformation: `Basic Information`,
	bookmarks: `Bookmarks`,
	bookmarksUpdated: `Bookmarks Updated`,
	chooseFiles: `Choose Files`,
	chooseTopics: `Choose Topics`,
	close: `Close`,
	closePreview: `Close Preview`,
	collection: {
		subheader1: `Collection`,
		success: `Collection saved!`,
		failure: `Collection failed to save.`,
	},
	collectionDetails: `Collection Details`,
	collectionDisclaimerHeader: `Disclaimer: Trading of Artifact Sponsorship`,
	collectionDisclaimerInfo: `Please be aware of the following terms and conditions when engaging in the trading of sponsorship for atomic assets mined from the Alex. Archive:<br><b>Ownership and Attribution:</b> All artifacts available on Alex Marketplace are atomic assets, and all associated rights are credited to the asset holder, identified by their (holdertagname) as specified in the asset metadata.<br><b>Artifact Sponsorship:</b> By participating as an artifact sponsor, you are assuming the responsibility of sponsoring the storage of digital content on the Arweave platform.<br><b>Trading Decisions:</b> The decision to trade the sponsorship of artifacts, on BazAR or any other marketplace is solely at the discretion of the artifact sponsors. Alex Archive, the platform operator, bears no responsibility for the outcomes or consequences of these trading activities.<br><b>Compliance with Licensing:</b> Artifact sponsors are required to adhere to all licensing requirements set forth by the content owner. It is essential to ensure that any sponsored content complies with the applicable licensing terms.<br>As a general guideline, only artifacts that fall within the public domain or for which the artifact sponsor has obtained proper licensing and permissions should be considered for trading. Unauthorized or infringing content may result in legal consequences.It is essential to exercise diligence and responsibility when engaging in any trading activities and to respect the rights and licenses associated with the digital content involved.`,
	collectionNameAlreadyExists: `Collection Name already exists`,
	collections: `Collections`,
	collectionCreated: `Collection Created`,
	comments: `Comments`,
	confirmTransfer: `Confirm Transfer`,
	connect: `Connect`,
	connectWallet: `Connect Wallet`,
	connectionError: `Connection Error`,
	contribute: `Contribute`,
	contributeTo: `Contribute to`,
	contributeView: {
		header1: `Contribute to a pool`,
		subHeader1: `<p>Anyone can contribute to a pool, which pays for the storage costs of its <span>artifacts</span>.`,
		subHeader2: `<b>Archiving is a public good</b>. Allowing people access to information about the past enables them to make higher
		quality decisions in the present. Currently, however, archiving is insufficiently incentivized: The person 
		that stores the data, which other's can later access without charge, is the person that has to pay.
		<b>Alex. changes this</b>. By allowing its community to become micro-sponsors of digital artifacts, an incentive is
		created for developers and creators to publically archive great digital works on Arweave.`,
		detail: {
			artifactTypes: `Artifacts are currently being preserved from:`,
			action: `Learn about Wallets`,
			section1: {
				header: 'What does it mean?',
				description:
					'Contributing means to send a portion of your <b>($AR)</b> to a pool. Contributions are used to pay for the storage costs of artifacts stored on Arweave. A portion of contributions also go to pool operators for their work.',
				footer: 'Artifacts are deployed as assets to Arweave and distributed to the contributors who support the pool.',
			},
			section2: {
				header: 'How to Contribute?',
				description1: `First, users will need an Arweave wallet with some <b>($AR)</b> in it to contribute. You can create a wallet at <a target="_blank" href=${ARCONNECT_REDIRECT}>arconnect.io</a> or <a target="_blank" href=${ARWEAVE_APP_REDIRECT}>arweave.app</a>. You can connect your wallet in Alex. by selecting <b>Connect Wallet</b> in the navigation menu.`,
				description2:
					'Next, you can select the <b>Contribute</b> button in any of the open pool pages. A window will appear which allows you to select the amount to contribute. This also shows the percentage of artifacts you will receive for contributing based on the amount of <b>($AR)</b> that you send.',
				description3:
					'After the contribution is received and the pool operator continues to mine artifacts, you will then be able to see your artifacts in your account.',
				description4: 'Learn more about how contributing works in our documentation.',
			},
			section3: {
				header: 'Why sponsor artifacts?',
				description:
					'Artifact sponsoring creates a new incentive for users to contribute to permanent archiving of digital content. <b>Anyone can contribute to pools and earn artifacts</b>. These artifacts can never be modified or removed as they are permanently stored on Arweave. Artifacts come in the form of documents, books, images, audio, videos, and more.',
			},
		},
		subnav: {
			header: `Contributing`,
			howItWorks: 'How it works',
		},
	},
	contributionMessage: `Your contribution totals will be adjusted once your transfer has settled on the Arweave network.`,
	contributionPercentage: `Management Fee`,
	contributionPercentageMessage: (percentage: string) =>
		`* This Pool Operator will claim ${percentage}% of the contribution as a management fee.`,
	contributionPercentageTooltip: `This value represents a management fee of the contributions. This value can be from 0 - 100 and represents the total percentage of contributions that go to your control wallet for mining. If the value of Management Fee is 10, then 10% of all contributions will remain in your wallet as your personal funds. This percentage will appear in the user interface to let contributors know how much of their contribution will go to the operator.`,
	contributions: `Contributions`,
	contributors: {
		recent: `Recent Contributors`,
		top: `Top Contributors`,
	},
	connectorNotFound: `This connector was not found`,
	copied: `Copied!`,
	copyAddress: `Copy Address`,
	copyArtifactId: `Copy Artifact ID`,
	create: `Create`,
	createCollection: `Create a Collection`,
	createFirstCollection: `Create your first collection`,
	createListings: `Create Listings`,
	createPool: `Create a Pool`,
	createView: {
		header1: `Create with Alex.`,
		steps: {
			display: `Step`,
			list: [
				{
					header: `Think of a topic to archive`,
					description: `This can be a <span>historical event, current event, cultural topic, innovation, or anything that can be digitally preserved.</span> Once you have your topic, you must decide where you will mine the artifacts from. It can be from social media <span>(Twitter, Reddit, Nostr), websites (Wikipedia),</span> or your own <span>personal archive.</span>`,
					action: {
						label: `Current Pools`,
						href: `/pools`,
					},
				},
				{
					header: `Connect your wallet`,
					description: `Before building a pool, you must connect your Arweave wallet. You can connect your wallet in Alex. by selecting Connect Wallet in the navigation menu. You can create a wallet at <a target="_blank" href=${ARCONNECT_REDIRECT}>arconnect.io</a> or <a target="_blank" href=${ARWEAVE_APP_REDIRECT}>arweave.app</a>.`,
					action: {
						label: `Learn about Wallets`,
						href: `https://cookbook.arweave.dev/concepts/keyfiles-and-wallets.html`,
						targetBlank: true,
					},
				},
				{
					header: `Build the Pool`,
					description: `You can start building your pool from our pool creation page. This is where you will include all necessary information to display the pool on the pools page and start mining. This includes writing a description of the pool, including a header image, keywords, and determining the percentage of contributions that you will receive as a management fee.`,
					action: {
						label: `Create a Pool`,
						href: `/pools/create`,
					},
				},
				{
					header: `Fund the pool`,
					description: `Once a pool is configured and created, <span>($AR)</span> is needed to store the artifacts and run the mining processes. Contributors are encouraged to send a portion of their <span>($AR)</span> to pools to become sponsors of artifacts.`,
					action: {
						label: `Learn About Contributing`,
						href: `/docs/contributing`,
					},
				},
				{
					header: `Start archiving`,
					description: `Once you receive contributions, you can then begin archiving. You may upload files directly from the User Interface. Your pool can be found from the pools tab in your account. If you are archiving from social media, you can follow our documentation to archive from specific platforms. On your specific pool page you will see artifacts start to accrue. The key to running a successful pool is consistent and accurate archiving based on the pool topic.`,
					action: {
						label: `Visit Mining Documentation`,
						href: `/docs/creating-a-pool/mining-artifacts`,
					},
				},
			],
		},
		stepsHeader1: `How it works`,
		subHeader1: `<p>If you have an idea, topic or event that you would like to preserve forever, you can create a pool and earn <span>($AR)</span> for it.</p>`,
		subHeader2: `Anyone can create a pool with Alex. for any given topic/event. An operator creates a pool and mines artifacts into it. These artifacts are deployed as assets to Arweave and distributed to the contributors based on the amount of <b>$AR</b> contributed.`,
		subnav: {
			header: `Create with Alex.`,
			howItWorks: `How it works`,
		},
	},
	createdOn: `Created on`,
	dateCreated: `Date Created`,
	default: `Default`,
	details: `Details`,
	description: `Description`,
	disconnect: `Disconnect`,
	docs: `Docs`,
	docsTitle: `Documentation`,
	download: `Download`,
	downloadPoolConfig: `Download Pool Configuration`,
	downloadPoolConfigTooltip: `Download the necessary configuration file to operate this pool from the Alex. CLI`,
	editSelectedArtifacts: `Edit Selected Artifacts`,
	enterFullScreen: `Enter Full Screen`,
	errorFetchingArtifact: `Error Fetching Artifact`,
	errorOccurred: `Error Occurred`,
	exit: `Exit`,
	exploreMore: `Explore More`,
	factMarket: `Fact Market`,
	factMarketCreated: `Fact Market Created`,
	fetching: `Fetching`,
	fetchingBalance: `Fetching balance`,
	fetchingCount: `Fetching count`,
	fetchingReceivingPercentage: `Fetching receiving amount`,
	field: `Field`,
	fileName: `File Name`,
	filesUploading: `Files Uploading`,
	filesUploadingMessage: `This may take some time, please stay on this screen.`,
	filesUploadingMessageComplete: `Your artifacts have been created, it will take some time for them to settle on the Arweave network. Once they have, you will be able to find them in your pool.`,
	fileUploadComplete: `File Upload Complete!`,
	filesAndMetadata: `Files and Metadata`,
	filesSelected: `Files Selected`,
	filter: `Filter`,
	filterBy: `Filter By`,
	funded: `Funded`,
	fundsTransferFailedMessage: `There was a problem transferring your funds. It could be due to existing funds currently processing in the network.`,
	fundsTransferInitiatedMessage: `Your transfer has been initiated. It usually takes 20 - 30 minutes for the transfer to complete. You can verify the transfer by checking the Pool Balance progress bar on this screen.`,
	fundsTransferred: `Funds Transferred`,
	handle: `Handle`,
	headerImage: `Header Image`,
	invalidContributionPercentage: `This value can be between 0 and 100`,
	invalidMetadataField: `Metadata fields must be unique`,
	invalidQuery: `Invalid Query`,
	invalidTitle: `Invalid Title`,
	invalidWalletPoolManage: `You do not have permission to manage this pool`,
	keywordTooltip: `Keywords are relevant values to a pool used to search through different platforms while mining artifacts, they also are attached to each artifact in a pool.`,
	keywords: `Keywords`,
	landingView: {
		infoHeader1: `Contribute to a pool`,
		infoSubheader1: `Anyone can become a sponsor of artifacts.`,
		infoDescription1: `Pools are topics, events or ideas that are preserved digitally on Arweave. By contributing <b>($AR)</b> to pools, you pay for the storage space, and earn a stake in the artifacts mined into pools.`,
		infoAction1: `Learn How to Contribute`,
		infoHeader2: `Create a Pool`,
		infoSubheader2: `Anyone can start preserving artifacts.`,
		infoDescription2: `Anyone can start their own pool on any topic or idea they choose and earn <b>($AR)</b> for archiving. As the pool operator you can control what artifacts are mined and how much you earn.`,
		infoAction2: `Create a Pool`,
	},
	lastContribution: `Last Contribution`,
	learnAboutCreating: `Learn About Creating`,
	library: {
		header1: `Library`,
		all: { title: `All` },
		new: { title: `New` },
		bookmarks: { title: `Bookmarks` },
	},
	loading: `Loading`,
	loadMore: `Load more`,
	managePool: `Manage Pool`,
	maxTransferAmount: `Max Transfer Amount`,
	mediaCaution: `Caution: Media may contain inappropriate content.`,
	messaging: {
		handle: `Handle`,
		message: `Message`,
		name: `Name`,
		originalPostDate: `Original Post Date`,
	},
	metadataField: `Metadata Field`,
	metadataUpdated: `Metadata Updated`,
	miningSource: `Mining Source`,
	miningSources: {
		files: 'Files',
		twitter: 'Twitter',
		wikipedia: 'Wikipedia',
		reddit: 'Reddit',
		nostr: 'Nostr',
	},
	name: `Name`,
	navigation: `Navigation`,
	next: `Next`,
	noArtifacts: `No Artifacts`,
	noContributions: `No Contributions`,
	noPools: `No Pools`,
	ofArtifactsCreated: `of new Artifacts created`,
	openInNewTab: `Open in New Tab`,
	oppose: `Oppose`,
	owner: `Sponsor`,
	ownerInfo: `Owner Information`,
	pageNotFound: `Page Not Found`,
	paths: {
		about: `About`,
		contribute: `Contribute`,
		create: `Create`,
		docs: `Docs`,
		pools: `Pools`,
	},
	pause: `Pause`,
	play: `Play`,
	pool: {
		subheader1: `Pool`,
		artifactsCreated: `Artifacts Created`,
		contribute: {
			notEnoughFunds: `Not enough AR to contribute to this pool.`,
			failed: `Failed to contribute to pool. Please try again.`,
			success: `Thank you for your contribution.`,
		},
	},
	poolBalance: `Pool Balance`,
	poolBalanceInfo: `This balance represents the funds currently available for mining use. Note that this balance only represents funds contributed to this Alex. pool and not your total wallet balance.<br><br> When contributions are made, these funds must be transferred onto the network before you can mine artifacts. This can be done by clicking ‘Transfer Funds’ from this screen.`,
	poolConfiguration: `Pool Configuration`,
	poolConfigurationInfo: `This configuration can be used for mining with the Alex. CLI. Please enter a Pool ID which will be used to identify the pool in the CLI.<br><br>After downloading this configuration, please visit our documentation for next steps. You will need to enter additional information into the configuration to successfully mine artifacts in the CLI.`,
	poolManage: {
		mine: { title: 'Mine Artifacts' },
		view: { title: 'View Artifacts' },
	},
	poolAlreadyExists: `This Pool Already Exists`,
	poolCreated: `Success, Pool Created!`,
	poolCreatedInfo: `Congratulations on starting a new pool! You will be able to start mining artifacts when the pool transaction has settled on the Arweave Network and a contribution to the pool has been made. You can find your pool from the pools tab on your account page, and you can being managing your pool by clicking Manage Pool below.`,
	poolId: `Pool ID`,
	poolOperator: `Alex. Pool Operator`,
	pools: {
		header1: `Pools`,
		gridTitles: {
			mostContributed: `Most Active`,
			newest: `Recently Added`,
		},
	},
	previewArtifact: `Preview Artifact`,
	previewCollection: `Preview Collection`,
	previous: `Previous`,
	price: `Price`,
	publish: `Publish`,
	ready: `Ready`,
	recentlyMintedArtifacts: `Recently Minted Artifacts`,
	receiving: `Receiving`,
	redditAuthor: `Posted by u/`,
	removeField: `Remove Field`,
	removeFile: `Remove File`,
	removeFromBookmarks: `Remove from Bookmarks`,
	save: `Save`,
	searchInitializing: `Initializing search`,
	select: `Select`,
	selectChooseFiles: `Select <b>Choose Files</b> to start uploading`,
	sellArtifact: `Sell Artifact`,
	sellArtifactDescription: `This order will be listed in the UCM for the specified amount of $U`,
	share: `Share`,
	shareArtifact: `Check out this Alex. Artifact !`,
	sharePool: `Check out this Alex. Pool !`,
	sharePools: `Check out these Alex. Pools !`,
	shareUrlLabel: `Share (Copy URL)`,
	showMoreReplies: `Show more replies`,
	siteTitle: `Alex.`,
	social: {
		discord: `Discord`,
		twitter: `Twitter`,
	},
	sortBy: `Sort By`,
	stamp: `STAMP`,
	stamps: `Stamps`,
	stampsVouched: `Vouched Stamps`,
	superStamp: `Super STAMP`,
	submit: `Submit`,
	success: `Success`,
	support: `Support`,
	tableOfContents: `Table of Contents`,
	title: `Title`,
	topic: `Topic`,
	topics: `Topics`,
	total: `Total`,
	totalContributed: `Total Contributed`,
	transferred: `Transferred`,
	transferFailed: `Transfer Failed`,
	transferFunds: `Transfer Funds`,
	transferPoolFunds: `Transfer Pool Funds`,
	transferPoolFundsInfo: `Contributions must be transferred onto the network before you can mine artifacts. You can select the maximum amount or enter a custom amount in the form below.`,
	transferInitiated: `Transfer Initiated`,
	type: `Type`,
	upload: `Upload`,
	uploadImage: `Upload Image`,
	updateMetadata: `Update Metadata`,
	upvoted: `Upvoted`,
	urlCopied: `URL Copied!`,
	uTokens: `$U`,
	value: `Value`,
	view: `View`,
	viewAccount: `View Account`,
	viewDocs: `View Docs`,
	viewOnArweave: `View on Arweave`,
	viewOnBazar: `View on BazAR`,
	viewOnPermafacts: `View on Permafacts`,
	viewPool: `View Pool`,
	visitDocs: `Visit Documentation`,
	volume: `Volume`,
	walletBalance: `Wallet Balance`,
	walletNotConnected: `Connect a wallet to continue`,
	willBeReceiving: `You will be receiving`,
};
