export const LANGUAGE = {
	about: `About`,
	artifactDetails: `Artifact Details`,
	artifactsCreated: `of Artifacts Created`,
	accept: `Accept`,
	account: {
		header1: `Account`,
		all: { title: `All` },
		collections: { title: `Collections` },
		new: { title: `New` },
		bookmarks: { title: `Bookmarks` },
		contributions: { title: `Contributions` },
	},
	actions: `Actions`,
	activePools: `Active Pools`,
	addtoBookmarks: `Add to Bookmarks`,
	amountExceedsBalance: `Amount exceeds Balance`,
	artifact: `Artifact`,
	artifactCount: `Artifact Count`,
	artifactGroup: `Artifact Group`,
	artifactPreview: `Artifact Preview`,
	artifactStamped: `Artifact Stamped`,
	artifacts: `Artifacts`,
	artifactDetail: {
		fileInformation: `File Information`,
		viewRaw: `View Raw`,
		tags: `Tags`,
		title: `Title`,
	},
	arTokens: `$AR`,
	availableBalance: `Available Balance`,
	banner: {
		header1: `Preserving`,
		header2: `Human History`,
		subheader1: `Archives are permanently stored on`,
		subheader2: `Pools are created with the`,
	},
	basicInformation: `Basic Information`,
	bookmarks: `Bookmarks`,
	bookmarksUpdated: `Bookmarks Updated`,
	close: `Close`,
	closePreview: `Close Preview`,
	collection: {
		subheader1: `Collection`,
		success: `Collection saved!`,
		failure: `Collection failed to save.`,
	},
	collectionDetails: `Collection Details`,
	collectionNameAlreadyExists: `Collection Name already exists`,
	collections: `Collections`,
	comments: `Comments`,
	companyTitle: `Alex.`,
	connect: `Connect`,
	connectWallet: `Connect Wallet`,
	connectionError: `Connection Error`,
	contribute: `Contribute`,
	contributeTo: `Contribute to`,
	contributionMessage: `Your contribution totals will be adjusted once your transfer has settled on the Arweave network.`,
	contributions: `Contributions`,
	contributors: {
		recent: `Recent Contributors`,
		top: `Top Contributors`,
	},
	copied: `Copied!`,
	copyAddress: `Copy Address`,
	copyArtifactId: `Copy Artifact ID`,
	create: `Create`,
	createCollection: `Create a Collection`,
	createFirstCollection: `Create your first collection`,
	createdOn: `Created on`,
	dateCreated: `Date Created`,
	default: `Default`,
	details: `Details`,
	description: `Description`,
	disconnect: `Disconnect`,
	editSelectedArtifacts: `Edit Selected Artifacts`,
	errorFetchingArtifact: `Error Fetching Artifact`,
	errorOccurred: `Error Occurred`,
	exit: `Exit`,
	factMarket: `Fact Market`,
	factMarketCreated: `Fact Market Created`,
	fetchingBalance: `Fetching balance`,
	fetchingCount: `Fetching count`,
	fetchingReceivingPercentage: `Fetching receiving amount`,
	info: {
		header1: `What is Alex. & How Does it Work?`,
		header2: `Those who cannot remember the past are condemned to repeat it.`,
		subheader: `<b>Alex.</b> The new fireproof Library of Alexandria`,
		content: `In 48 BC, humanity lost one of the greatest troves of human knowledge to a fire. We will never know the full extent of the culture, knowledge or history lost when the Library of Alexandria was destroyed, but we can learn from the past to better prepare for the future.<br><br>We’ve come a long way from centrally storing vast amounts of information on highly combustible mediums, but we still face a lot of the same challenges from antiquity; the manipulation, corruption or deletion of important information.<br><br>Alex. is a decentralized archival platform that leverages the immutable and permanent data storage of Arweave and includes a mechanism that encourages end user participation.<br><br>Users contribute to pools and they receive “artifacts” back into their wallet as they are minted. Artifacts are pieces of information the pool is storing. Since the artifacts are stored on Arweave, they cannot be changed or removed in any way by anyone.<br><br>This is the continuation of the dream that was the Great Library of Alexandria. In order for us to move forward and continue making better decisions we need the ability to clearly see our past.<br><br><b>Alex.</b><br><br>Always accessible. Never changing. Never deleted.`,
		assetSrc: `A 19th century illustration of the burning of the Library of Alexandria. Heritage Images/Getty Images.`,
	},
	invalidQuery: `Invalid Query`,
	lastContribution: `Last Contribution`,
	library: {
		header1: `Library`,
		all: { title: `All` },
		new: { title: `New` },
		bookmarks: { title: `Bookmarks` },
	},
	loading: `Loading`,
	loadMore: `Load more`,
	mediaCaution: `Caution: Media may contain inappropriate content.`,
	messaging: {
		handle: `Handle`,
		message: `Message`,
		name: `Name`,
		originalPostDate: `Original Post Date`,
	},
	name: `Name`,
	next: `Next`,
	noArtifacts: `No Artifacts`,
	noContributions: `No Contributions`,
	ofArtifactsCreated: `of new Artifacts created`,
	openInNewTab: `Open in New Tab`,
	oppose: `Oppose`,
	owner: `Sponsor`,
	pageNotFound: `Page Not Found`,
	paths: {
		pools: `Pools`,
	},
	pool: {
		subheader1: `Pool`,
		artifactsCreated: `Artifacts Created`,
		contribute: {
			notEnoughFunds: `Not enough AR to contribute to this pool.`,
			failed: `Failed to contribute to pool. Please try again.`,
			success: `Thank you for your contribution.`,
		},
	},
	poolOperator: `Alex. Pool Operator`,
	pools: {
		header1: `Pools`,
		gridTitles: {
			all: `All`,
			mostContributed: `Most Active`,
			newest: `Newest`,
		},
	},
	previewArtifact: `Preview Artifact`,
	previewCollection: `Preview Collection`,
	previous: `Previous`,
	publish: `Publish`,
	recentlyMintedArtifacts: `Recently Minted Artifacts`,
	receiving: `Receiving`,
	redditAuthor: `Posted by u/`,
	removeFromBookmarks: `Remove from Bookmarks`,
	save: `Save`,
	searchInitializing: `Initializing search`,
	select: `Select`,
	share: `Share`,
	shareArtifact: `Check out this Alex. Artifact !`,
	sharePools: `Check out this Alex. Pool !`,
	shareUrlLabel: `Share (Copy URL)`,
	showing: `Showing`,
	showMoreReplies: `Show more replies`,
	social: {
		discord: `Discord`,
		twitter: `Twitter`,
	},
	sortBy: `Sort By`,
	stamp: `STAMP`,
	stamps: `Stamps`,
	stampsVouched: `Vouched Stamps`,
	superStamp: `Super STAMP`,
	steps: {
		header1: `A New Way to Get Involved in the Human Story`,
		header2: `Alex. offers a unique way for everyone to participate and "own" a piece of the human story. By supporting the participating archival institutions, you are helping protect our history from edits, omissions, narratives, & malicious intent. <b>Here&#8217;s how.</b>`,
		display: `Step`,
		list: [
			`<b>Contributors</b> send $AR tokens to any participating <b>Archival Institution.</b> There is no limit on how many or how few a contributor may send.`,
			`These tokens are used to pay for the storage costs on <b>Arweave.</b> Using blockweave technology, Arweave is the only place where files cannot be changed or deleted once they are uploaded. <span>There are no reccuring costs.</span> Pay once, store forever.`,
			`Documents, books, images, audio clips, videos, etc. within the institution&#8217;s pool are uploaded to Arweave. We refer to these files as <b>Artifacts</b>.`,
			`<b>These Artifacts are randomly sent to participating contributor&#8217;s wallets.</b> Contributors will receive an equal percentage of their $AR contribution (relative to the total $AR contributed) in digital artifacts. For example: If John contributed 10 $AR tokens and the total amount contributed was 100 $AR tokens, John will receive 10% of the Artifacts into his wallet.`,
		],
	},
	submit: `Submit`,
	support: `Support`,
	title: `Title`,
	topic: `Topic`,
	total: `Total`,
	totalContributed: `Total Contributed`,
	type: `Type`,
	upvoted: `Upvoted`,
	urlCopied: `URL Copied!`,
	view: `View`,
	viewAccount: `Account`,
	viewOnArweave: `View on Arweave`,
	viewOnPermafacts: `View on Permafacts`,
	viewPool: `View Pool`,
	walletNotConnected: `Connect a wallet to continue`,
	willBeReceiving: `You will be receiving`,
};
