export const base = '/';
export const about = `${base}about/`;
export const account = `${base}account/`;
export const accountAll = `${account}all/`;
export const accountBookmarks = `${account}bookmarks/`;
export const accountCollections = `${account}collections/`;
export const accountContributions = `${account}contributions/`;
export const accountPools = `${account}pools/`;
export const artifact = `${base}artifact/`;
export const collections = `${base}collections/`;
export const collectionsManage = `${collections}manage`;
export const contribute = `${base}contribute/`;
export const create = `${base}create/`;
export const docs = `${base}docs/`;
export const library = `${base}library/`;
export const libraryAll = (id: string) => `${library}${id}/all/`;
export const libraryBookmarks = (id: string) => `${library}${id}/collections/`;
export const pool = `${base}pool/`;
export const poolManage = `${pool}manage/`;
export const poolManageMine = (id: string) => `${poolManage}${id}/mine/`;
export const poolManageView = (id: string) => `${poolManage}${id}/view/`;
export const pools = `${base}pools/`;
export const poolsCreate = `${pools}create/`;
export const thread = `${base}thread/`;
