export const base = '/';
export const about = `${base}about/`;
export const account = `${base}account/`;
export const accountAll = `${account}all/`;
export const accountCollections = `${account}collections/`;
export const accountNew = `${account}new/`;
export const accountBookmarks = `${account}bookmarks/`;
export const accountContributions = `${account}contributions/`;
export const artifact = `${base}artifact/`;
export const collections = `${base}collections/`;
export const collectionsManage = `${collections}manage`;
export const create = `${base}create/`;
export const library = `${base}library/`;
export const libraryAll = (id: string) => `${library}${id}/all/`;
export const libraryBookmarks = (id: string) => `${library}${id}/collections/`;
export const pool = `${base}pool/`;
export const pools = `${base}pools/`;
export const thread = `${base}thread/`;
