name: publish 

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: npm i
      - run: npm run deploy
        env:
          KEY: ${{ secrets.ALEX_DEPLOY_KEY }}
